// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
<<<<<<< HEAD
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
=======
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
>>>>>>> 66a93519c12a0a7e774e8b3604b8c28595a49ad6
// source: proto/slice_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NumbersRequest 包含数字切片
type NumbersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numbers       []int32                `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	NumbersIsNil  bool                   `protobuf:"varint,2,opt,name=numbers_is_nil,json=numbersIsNil,proto3" json:"numbers_is_nil,omitempty"` // 显式标记客户端发送的是否为 nil
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumbersRequest) Reset() {
	*x = NumbersRequest{}
	mi := &file_proto_slice_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumbersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumbersRequest) ProtoMessage() {}

func (x *NumbersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_slice_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumbersRequest.ProtoReflect.Descriptor instead.
func (*NumbersRequest) Descriptor() ([]byte, []int) {
	return file_proto_slice_service_proto_rawDescGZIP(), []int{0}
}

func (x *NumbersRequest) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

<<<<<<< HEAD
func (x *NumbersRequest) GetNumbersIsNil() bool {
	if x != nil {
		return x.NumbersIsNil
	}
	return false
}
=======
// NumbersResponse 返回处理后的数字切片
type NumbersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
>>>>>>> 66a93519c12a0a7e774e8b3604b8c28595a49ad6

// NumbersResponse 返回处理后的数字切片
type NumbersResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProcessedNumbers []int32                `protobuf:"varint,1,rep,packed,name=processed_numbers,json=processedNumbers,proto3" json:"processed_numbers,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IsNil            bool                   `protobuf:"varint,3,opt,name=is_nil,json=isNil,proto3" json:"is_nil,omitempty"`
	SliceLength      int32                  `protobuf:"varint,4,opt,name=slice_length,json=sliceLength,proto3" json:"slice_length,omitempty"`
	SliceCapacity    int32                  `protobuf:"varint,5,opt,name=slice_capacity,json=sliceCapacity,proto3" json:"slice_capacity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NumbersResponse) Reset() {
	*x = NumbersResponse{}
	mi := &file_proto_slice_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumbersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumbersResponse) ProtoMessage() {}

func (x *NumbersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_slice_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumbersResponse.ProtoReflect.Descriptor instead.
func (*NumbersResponse) Descriptor() ([]byte, []int) {
	return file_proto_slice_service_proto_rawDescGZIP(), []int{1}
}

func (x *NumbersResponse) GetProcessedNumbers() []int32 {
	if x != nil {
		return x.ProcessedNumbers
	}
	return nil
}

func (x *NumbersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

<<<<<<< HEAD
func (x *NumbersResponse) GetIsNil() bool {
	if x != nil {
		return x.IsNil
	}
	return false
}
=======
// StringsRequest 包含字符串切片
type StringsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
>>>>>>> 66a93519c12a0a7e774e8b3604b8c28595a49ad6

func (x *NumbersResponse) GetSliceLength() int32 {
	if x != nil {
		return x.SliceLength
	}
	return 0
}

func (x *NumbersResponse) GetSliceCapacity() int32 {
	if x != nil {
		return x.SliceCapacity
	}
	return 0
}

// StringsRequest 包含字符串切片
type StringsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strings       []string               `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
	StringsIsNil  bool                   `protobuf:"varint,2,opt,name=strings_is_nil,json=stringsIsNil,proto3" json:"strings_is_nil,omitempty"` // 显式标记客户端发送的是否为 nil
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringsRequest) Reset() {
	*x = StringsRequest{}
	mi := &file_proto_slice_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringsRequest) ProtoMessage() {}

func (x *StringsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_slice_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringsRequest.ProtoReflect.Descriptor instead.
func (*StringsRequest) Descriptor() ([]byte, []int) {
	return file_proto_slice_service_proto_rawDescGZIP(), []int{2}
}

func (x *StringsRequest) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

<<<<<<< HEAD
func (x *StringsRequest) GetStringsIsNil() bool {
	if x != nil {
		return x.StringsIsNil
	}
	return false
}
=======
// StringsResponse 返回处理后的字符串切片
type StringsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
>>>>>>> 66a93519c12a0a7e774e8b3604b8c28595a49ad6

// StringsResponse 返回处理后的字符串切片
type StringsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProcessedStrings []string               `protobuf:"bytes,1,rep,name=processed_strings,json=processedStrings,proto3" json:"processed_strings,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IsNil            bool                   `protobuf:"varint,3,opt,name=is_nil,json=isNil,proto3" json:"is_nil,omitempty"`
	SliceLength      int32                  `protobuf:"varint,4,opt,name=slice_length,json=sliceLength,proto3" json:"slice_length,omitempty"`
	SliceCapacity    int32                  `protobuf:"varint,5,opt,name=slice_capacity,json=sliceCapacity,proto3" json:"slice_capacity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StringsResponse) Reset() {
	*x = StringsResponse{}
	mi := &file_proto_slice_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringsResponse) ProtoMessage() {}

func (x *StringsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_slice_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringsResponse.ProtoReflect.Descriptor instead.
func (*StringsResponse) Descriptor() ([]byte, []int) {
	return file_proto_slice_service_proto_rawDescGZIP(), []int{3}
}

func (x *StringsResponse) GetProcessedStrings() []string {
	if x != nil {
		return x.ProcessedStrings
	}
	return nil
}

func (x *StringsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StringsResponse) GetIsNil() bool {
	if x != nil {
		return x.IsNil
	}
	return false
}

func (x *StringsResponse) GetSliceLength() int32 {
	if x != nil {
		return x.SliceLength
	}
	return 0
}

func (x *StringsResponse) GetSliceCapacity() int32 {
	if x != nil {
		return x.SliceCapacity
	}
	return 0
}

var File_proto_slice_service_proto protoreflect.FileDescriptor

<<<<<<< HEAD
const file_proto_slice_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/slice_service.proto\x12\fsliceservice\"P\n" +
	"\x0eNumbersRequest\x12\x18\n" +
	"\anumbers\x18\x01 \x03(\x05R\anumbers\x12$\n" +
	"\x0enumbers_is_nil\x18\x02 \x01(\bR\fnumbersIsNil\"\xb9\x01\n" +
	"\x0fNumbersResponse\x12+\n" +
	"\x11processed_numbers\x18\x01 \x03(\x05R\x10processedNumbers\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06is_nil\x18\x03 \x01(\bR\x05isNil\x12!\n" +
	"\fslice_length\x18\x04 \x01(\x05R\vsliceLength\x12%\n" +
	"\x0eslice_capacity\x18\x05 \x01(\x05R\rsliceCapacity\"P\n" +
	"\x0eStringsRequest\x12\x18\n" +
	"\astrings\x18\x01 \x03(\tR\astrings\x12$\n" +
	"\x0estrings_is_nil\x18\x02 \x01(\bR\fstringsIsNil\"\xb9\x01\n" +
	"\x0fStringsResponse\x12+\n" +
	"\x11processed_strings\x18\x01 \x03(\tR\x10processedStrings\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06is_nil\x18\x03 \x01(\bR\x05isNil\x12!\n" +
	"\fslice_length\x18\x04 \x01(\x05R\vsliceLength\x12%\n" +
	"\x0eslice_capacity\x18\x05 \x01(\x05R\rsliceCapacity2\xa6\x01\n" +
	"\fSliceService\x12J\n" +
	"\vEchoNumbers\x12\x1c.sliceservice.NumbersRequest\x1a\x1d.sliceservice.NumbersResponse\x12J\n" +
	"\vEchoStrings\x12\x1c.sliceservice.StringsRequest\x1a\x1d.sliceservice.StringsResponseB\x0fZ\rplayground/pbb\x06proto3"
=======
var file_proto_slice_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x6c, 0x69,
	0x63, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x21, 0x0a, 0x0e, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0f, 0x0a, 0x07, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x22, 0x4f, 0x0a, 0x0f,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2b, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x0f, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x22, 0x21, 0x0a,
	0x0e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0f, 0x0a, 0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x22, 0x4f, 0x0a, 0x0f, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64,
	0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73,
	0x12, 0x0f, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x32, 0xac, 0x01, 0x0a, 0x0c, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x2e, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4d, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x73, 0x12, 0x1c, 0x2e, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}
>>>>>>> 66a93519c12a0a7e774e8b3604b8c28595a49ad6

var (
	file_proto_slice_service_proto_rawDescOnce sync.Once
	file_proto_slice_service_proto_rawDescData []byte
)

func file_proto_slice_service_proto_rawDescGZIP() []byte {
	file_proto_slice_service_proto_rawDescOnce.Do(func() {
		file_proto_slice_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_slice_service_proto_rawDesc), len(file_proto_slice_service_proto_rawDesc)))
	})
	return file_proto_slice_service_proto_rawDescData
}

var file_proto_slice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_slice_service_proto_goTypes = []any{
	(*NumbersRequest)(nil),  // 0: sliceservice.NumbersRequest
	(*NumbersResponse)(nil), // 1: sliceservice.NumbersResponse
	(*StringsRequest)(nil),  // 2: sliceservice.StringsRequest
	(*StringsResponse)(nil), // 3: sliceservice.StringsResponse
}
var file_proto_slice_service_proto_depIdxs = []int32{
	0, // 0: sliceservice.SliceService.EchoNumbers:input_type -> sliceservice.NumbersRequest
	2, // 1: sliceservice.SliceService.EchoStrings:input_type -> sliceservice.StringsRequest
	1, // 2: sliceservice.SliceService.EchoNumbers:output_type -> sliceservice.NumbersResponse
	3, // 3: sliceservice.SliceService.EchoStrings:output_type -> sliceservice.StringsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_slice_service_proto_init() }
func file_proto_slice_service_proto_init() {
	if File_proto_slice_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_slice_service_proto_rawDesc), len(file_proto_slice_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_slice_service_proto_goTypes,
		DependencyIndexes: file_proto_slice_service_proto_depIdxs,
		MessageInfos:      file_proto_slice_service_proto_msgTypes,
	}.Build()
	File_proto_slice_service_proto = out.File
	file_proto_slice_service_proto_goTypes = nil
	file_proto_slice_service_proto_depIdxs = nil
}
