// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/slice_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SliceService_ProcessNumbers_FullMethodName = "/sliceservice.SliceService/ProcessNumbers"
	SliceService_ProcessStrings_FullMethodName = "/sliceservice.SliceService/ProcessStrings"
)

// SliceServiceClient is the client API for SliceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SliceServiceClient interface {
	// ProcessNumbers 接收一个数字切片，返回处理后的数字切片
	ProcessNumbers(ctx context.Context, in *NumbersRequest, opts ...grpc.CallOption) (*NumbersResponse, error)
	// ProcessStrings 接收一个字符串切片，返回处理后的字符串切片
	ProcessStrings(ctx context.Context, in *StringsRequest, opts ...grpc.CallOption) (*StringsResponse, error)
}

type sliceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSliceServiceClient(cc grpc.ClientConnInterface) SliceServiceClient {
	return &sliceServiceClient{cc}
}

func (c *sliceServiceClient) ProcessNumbers(ctx context.Context, in *NumbersRequest, opts ...grpc.CallOption) (*NumbersResponse, error) {
	out := new(NumbersResponse)
	err := c.cc.Invoke(ctx, SliceService_ProcessNumbers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sliceServiceClient) ProcessStrings(ctx context.Context, in *StringsRequest, opts ...grpc.CallOption) (*StringsResponse, error) {
	out := new(StringsResponse)
	err := c.cc.Invoke(ctx, SliceService_ProcessStrings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SliceServiceServer is the server API for SliceService service.
// All implementations must embed UnimplementedSliceServiceServer
// for forward compatibility
type SliceServiceServer interface {
	// ProcessNumbers 接收一个数字切片，返回处理后的数字切片
	ProcessNumbers(context.Context, *NumbersRequest) (*NumbersResponse, error)
	// ProcessStrings 接收一个字符串切片，返回处理后的字符串切片
	ProcessStrings(context.Context, *StringsRequest) (*StringsResponse, error)
	mustEmbedUnimplementedSliceServiceServer()
}

// UnimplementedSliceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSliceServiceServer struct {
}

func (UnimplementedSliceServiceServer) ProcessNumbers(context.Context, *NumbersRequest) (*NumbersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessNumbers not implemented")
}
func (UnimplementedSliceServiceServer) ProcessStrings(context.Context, *StringsRequest) (*StringsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessStrings not implemented")
}
func (UnimplementedSliceServiceServer) mustEmbedUnimplementedSliceServiceServer() {}

// UnsafeSliceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SliceServiceServer will
// result in compilation errors.
type UnsafeSliceServiceServer interface {
	mustEmbedUnimplementedSliceServiceServer()
}

func RegisterSliceServiceServer(s grpc.ServiceRegistrar, srv SliceServiceServer) {
	s.RegisterService(&SliceService_ServiceDesc, srv)
}

func _SliceService_ProcessNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SliceServiceServer).ProcessNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SliceService_ProcessNumbers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SliceServiceServer).ProcessNumbers(ctx, req.(*NumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SliceService_ProcessStrings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SliceServiceServer).ProcessStrings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SliceService_ProcessStrings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SliceServiceServer).ProcessStrings(ctx, req.(*StringsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SliceService_ServiceDesc is the grpc.ServiceDesc for SliceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SliceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sliceservice.SliceService",
	HandlerType: (*SliceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessNumbers",
			Handler:    _SliceService_ProcessNumbers_Handler,
		},
		{
			MethodName: "ProcessStrings",
			Handler:    _SliceService_ProcessStrings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/slice_service.proto",
}
