// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/slice_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumbersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Numbers []int32 `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
}

func (x *NumbersRequest) Reset() {
	*x = NumbersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_slice_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumbersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumbersRequest) ProtoMessage() {}

func (x *NumbersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_slice_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*NumbersRequest) Descriptor() ([]byte, []int) {
	return file_proto_slice_service_proto_rawDescGZIP(), []int{0}
}

func (x *NumbersRequest) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

type NumbersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessedNumbers []int32 `protobuf:"varint,1,rep,packed,name=processed_numbers,json=processedNumbers,proto3" json:"processed_numbers,omitempty"`
	Message          string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *NumbersResponse) Reset() {
	*x = NumbersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_slice_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumbersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumbersResponse) ProtoMessage() {}

func (x *NumbersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_slice_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*NumbersResponse) Descriptor() ([]byte, []int) {
	return file_proto_slice_service_proto_rawDescGZIP(), []int{1}
}

func (x *NumbersResponse) GetProcessedNumbers() []int32 {
	if x != nil {
		return x.ProcessedNumbers
	}
	return nil
}

func (x *NumbersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StringsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Strings []string `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
}

func (x *StringsRequest) Reset() {
	*x = StringsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_slice_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringsRequest) ProtoMessage() {}

func (x *StringsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_slice_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*StringsRequest) Descriptor() ([]byte, []int) {
	return file_proto_slice_service_proto_rawDescGZIP(), []int{2}
}

func (x *StringsRequest) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

type StringsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessedStrings []string `protobuf:"bytes,1,rep,name=processed_strings,json=processedStrings,proto3" json:"processed_strings,omitempty"`
	Message          string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StringsResponse) Reset() {
	*x = StringsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_slice_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringsResponse) ProtoMessage() {}

func (x *StringsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_slice_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*StringsResponse) Descriptor() ([]byte, []int) {
	return file_proto_slice_service_proto_rawDescGZIP(), []int{3}
}

func (x *StringsResponse) GetProcessedStrings() []string {
	if x != nil {
		return x.ProcessedStrings
	}
	return nil
}

func (x *StringsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_slice_service_proto protoreflect.FileDescriptor

var file_proto_slice_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x6c, 0x69,
	0x63, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x2c, 0x0a, 0x0e, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x07, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x5d, 0x0a, 0x0f, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x2c, 0x0a, 0x0e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x5d, 0x0a, 0x0f, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e,
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x65, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1a, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xb0, 0x01, 0x0a, 0x0c, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x2e, 0x73, 0x6c, 0x69, 0x63, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x01, 0x12, 0x50, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1c, 0x2e, 0x73, 0x6c, 0x69, 0x63,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x6c, 0x61, 0x79,
	0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_slice_service_proto_rawDescOnce sync.Once
	file_proto_slice_service_proto_rawDescData = file_proto_slice_service_proto_rawDesc
)

func file_proto_slice_service_proto_rawDescGZIP() []byte {
	file_proto_slice_service_proto_rawDescOnce.Do(func() {
		file_proto_slice_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_slice_service_proto_rawDescData)
	})
	return file_proto_slice_service_proto_rawDescData
}

var file_proto_slice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_slice_service_proto_goTypes = []interface{}{
	(*NumbersRequest)(nil),  // 0: sliceservice.NumbersRequest
	(*NumbersResponse)(nil), // 1: sliceservice.NumbersResponse
	(*StringsRequest)(nil),  // 2: sliceservice.StringsRequest
	(*StringsResponse)(nil), // 3: sliceservice.StringsResponse
}
var file_proto_slice_service_proto_depIdxs = []int32{
	0, // 0: sliceservice.SliceService.ProcessNumbers:input_type -> sliceservice.NumbersRequest
	2, // 1: sliceservice.SliceService.ProcessStrings:input_type -> sliceservice.StringsRequest
	1, // 2: sliceservice.SliceService.ProcessNumbers:output_type -> sliceservice.NumbersResponse
	3, // 3: sliceservice.SliceService.ProcessStrings:output_type -> sliceservice.StringsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_slice_service_proto_init() }
func file_proto_slice_service_proto_init() {
	if File_proto_slice_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_slice_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumbersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_slice_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumbersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_slice_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_slice_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_slice_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_slice_service_proto_goTypes,
		DependencyIndexes: file_proto_slice_service_proto_depIdxs,
		MessageInfos:      file_proto_slice_service_proto_msgTypes,
	}.Build()
	File_proto_slice_service_proto = out.File
	file_proto_slice_service_proto_rawDesc = nil
	file_proto_slice_service_proto_goTypes = nil
	file_proto_slice_service_proto_depIdxs = nil
}
