// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SliceServiceClient is the client API for SliceService service.
type SliceServiceClient interface {
	// ProcessNumbers 接收一个数字切片，返回处理后的数字切片
	ProcessNumbers(ctx context.Context, in *NumbersRequest, opts ...grpc.CallOption) (*NumbersResponse, error)
	// ProcessStrings 接收一个字符串切片，返回处理后的字符串切片
	ProcessStrings(ctx context.Context, in *StringsRequest, opts ...grpc.CallOption) (*StringsResponse, error)
}

type sliceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSliceServiceClient(cc grpc.ClientConnInterface) SliceServiceClient {
	return &sliceServiceClient{cc}
}

func (c *sliceServiceClient) ProcessNumbers(ctx context.Context, in *NumbersRequest, opts ...grpc.CallOption) (*NumbersResponse, error) {
	out := new(NumbersResponse)
	err := c.cc.Invoke(ctx, "/sliceservice.SliceService/ProcessNumbers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sliceServiceClient) ProcessStrings(ctx context.Context, in *StringsRequest, opts ...grpc.CallOption) (*StringsResponse, error) {
	out := new(StringsResponse)
	err := c.cc.Invoke(ctx, "/sliceservice.SliceService/ProcessStrings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SliceServiceServer is the server API for SliceService service.
type SliceServiceServer interface {
	// ProcessNumbers 接收一个数字切片，返回处理后的数字切片
	ProcessNumbers(context.Context, *NumbersRequest) (*NumbersResponse, error)
	// ProcessStrings 接收一个字符串切片，返回处理后的字符串切片
	ProcessStrings(context.Context, *StringsRequest) (*StringsResponse, error)
}

// UnimplementedSliceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSliceServiceServer struct {
}

func (*UnimplementedSliceServiceServer) ProcessNumbers(context.Context, *NumbersRequest) (*NumbersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessNumbers not implemented")
}

func (*UnimplementedSliceServiceServer) ProcessStrings(context.Context, *StringsRequest) (*StringsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessStrings not implemented")
}

func RegisterSliceServiceServer(s *grpc.Server, srv SliceServiceServer) {
	s.RegisterService(&_SliceService_serviceDesc, srv)
}

func _SliceService_ProcessNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SliceServiceServer).ProcessNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sliceservice.SliceService/ProcessNumbers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SliceServiceServer).ProcessNumbers(ctx, req.(*NumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SliceService_ProcessStrings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SliceServiceServer).ProcessStrings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sliceservice.SliceService/ProcessStrings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SliceServiceServer).ProcessStrings(ctx, req.(*StringsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SliceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sliceservice.SliceService",
	HandlerType: (*SliceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessNumbers",
			Handler:    _SliceService_ProcessNumbers_Handler,
		},
		{
			MethodName: "ProcessStrings",
			Handler:    _SliceService_ProcessStrings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/slice_service.proto",
}
